server:
  port: 8090
spring:
  application:
    name: banking_loans
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/loans
    username: michael
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true



